version: "3.8"

# TODO add nginx or caddy
# TODO add env and git secrets
# TODO add frontend deploy

networks:
  keycloak_network: {}
    

services:
  mariadb:
    # <<: *service
    image: mariadb
    deploy:      
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
    - ./var.env
    volumes:
      - ./volumes/mariadb:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "--silent"]
    networks:
      - keycloak_network
  keycloak:
    # <<: *service
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 8081:8080
    env_file:
    - ./var.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - keycloak_network
    depends_on:
      - mariadb
  mongo:
    # <<: *service
    image: mongo
    deploy:
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
    ports:
      - 27017:27017
    env_file:
    - ./var.env
    volumes:
      - ./volumes/mongo:/data/db